# Generated by Django 3.1.3 on 2021-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Air Conditioner', 'Air Conditioner'), ('Android', 'Android'), ('Audio', 'Audio'), ('Blender', 'Blender'), ('Bed/Mattress', 'Bed/Mattress'), ('Body Cream', 'Body Cream'), ('Clothing', 'Clothing'), ('Cooker', 'Cooker'), ('Desktop', 'Desktop'), ('Dispenser', 'Dispenser'), ('Fabrics', 'Fabrics'), ('Fans', 'Fans'), ('Food', 'Food'), ('Footwear', 'Footwear'), ('Fragrance', 'Fragrance'), ('Freezer', 'Freezer'), ('Fruit', 'Fruit'), ('Furniture', 'Furniture'), ('Fruits', 'Fruits'), ('IOS', 'IOS'), ('Jeans', 'Jeans'), ('Kettle', 'Kettle'), ('Laptop', 'Laptop'), ('Lingerie', 'Lingerie'), ('Microwave', 'Microwave'), ('Networking', 'Networking'), ('Refrigerator', 'Refrigerator'), ('Server', 'Server'), ('Shirts', 'Shirts'), ('T-Shirts', 'T-Shirts'), ('Television', 'Television'), ('Trousers', 'Trousers'), ('Vegetable', 'Vegetable'), ('Washing Machine', 'Washing Machine'), ('Watch', 'Watch'), ('Wigs', 'Wigs')], max_length=120),
        ),
    ]
