# Generated by Django 3.1.3 on 2020-12-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_product',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
