# Generated by Django 3.0.4 on 2020-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201008_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Beauty', 'Beauty'), ('Computer/Laptops', 'Computer/Laptops'), ('electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Flight', 'Flight'), ('Food', 'Food'), ('Home Appliances', 'Home Appliances'), ('Hotel', 'Hotel'), ('Kitchen appliances', 'Kitchen Appliances'), ('Phones/Tablets', 'Phones/Tablets')], max_length=25, null=True),
        ),
    ]
