# Generated by Django 3.1.3 on 2021-03-04 14:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201216_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_one',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[230, 192], upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_three',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[230, 192], upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_two',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[230, 192], upload_to='media'),
        ),
    ]
