# Generated by Django 3.0.4 on 2020-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201009_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Beauty', 'Beauty'), ('Computer/Laptops', 'Computer/Laptops'), ('electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Flight', 'Flight'), ('Food', 'Food'), ('Fruits', 'Fruits'), ('Home Appliances', 'Home Appliances'), ('Hotel', 'Hotel'), ('Kitchen appliances', 'Kitchen Appliances'), ('Phones/Tablets', 'Phones/Tablets')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Air Conditioner', 'Air Conditioner'), ('Android', 'Android'), ('Audio', 'Audio'), ('Blender', 'Blender'), ('Bed/Mattress', 'Bed/Mattress'), ('Clothing', 'Clothing'), ('Cooker', 'Cooker'), ('Desktop', 'Desktop'), ('Dispenser', 'Dispenser'), ('Fabrics', 'Fabrics'), ('Fans', 'Fans'), ('Footwear', 'Footwear'), ('Fragrance', 'Fragrance'), ('Freezer', 'Freezer'), ('Fruit', 'Fruit'), ('Furniture', 'Furniture'), ('IOS', 'IOS'), ('Kettle', 'Kettle'), ('Laptop', 'Laptop'), ('Microwave', 'Microwave'), ('Networking', 'Networking'), ('Refrigerator', 'Refrigerator'), ('Server', 'Server'), ('Television', 'Television'), ('Washers', 'Washers'), ('Watch', 'Watch')], max_length=120),
        ),
    ]
