# Generated by Django 3.1.3 on 2020-11-13 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, choices=[('Access Bank', 'Access Bank'), ('Citibank', 'Citibank'), ('Diamond Bank', 'Diamond Bank'), ('Ecobank Nigeria', 'Ecobank Nigeria'), ('Fidelity Bank Nigeria', 'Fidelity Bank Nigeria'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('First City Monument Bank', 'First City Monument Bank'), ('Guaranty Trust Bank', 'Guaranty Trust Bank'), ('Heritage Bank Plc', 'Heritage Bank Plc'), ('Jaiz Bank', 'Jaiz Bank'), ('Keystone Bank Limited', 'Keystone Bank Limited'), ('Providus Bank Plc', 'Providus Bank Plc'), ('Polaris Bank', 'Polaris Bank'), ('Stanbic IBTC Bank Nigeria Limited', 'Stanbic IBTC Bank Nigeria Limited'), ('Standard Bank', 'Standard Bank'), ('Standard Chartered Bank', 'Standard Chartered Bank'), ('Sterling Bank', 'Sterling Bank'), ('Suntrust Bank Nigeria Limited', 'Suntrust Bank Nigeria Limited'), ('Union Bank of Nigeria', 'Union Bank of Nigeria'), ('United Bank for Africa', 'United Bank for Africa'), ('Unity Bank Plc', 'Unity Bank Plc'), ('Wema Bank', 'Wema Bank'), ('Zenith Bank', 'Zenith Bank')], max_length=50, null=True)),
                ('account_number', models.IntegerField()),
                ('bvn', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
