# Generated by Django 3.1.3 on 2021-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='categories',
            field=models.ManyToManyField(to='product.Category'),
        ),
    ]
