# Generated by Django 3.1.3 on 2021-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_market_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='address',
            field=models.CharField(default='463 Ikorodu Road, Ketu, Lagos', max_length=140),
        ),
    ]
