# Generated by Django 3.0.4 on 2020-10-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price_offer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_picked', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('destination_address', models.CharField(max_length=255)),
                ('pickup_address', models.CharField(max_length=255)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
