# Generated by Django 3.0.4 on 2020-10-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_shopper', models.BooleanField(default=False)),
                ('is_merchant', models.BooleanField(default=False)),
                ('is_manufacturer', models.BooleanField(default=False)),
                ('is_shipper', models.BooleanField(default=False)),
                ('is_distributor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('bio', models.CharField(blank=True, max_length=256, null=True)),
                ('company_reg', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_number', models.IntegerField()),
                ('registration_number', models.IntegerField()),
                ('registration_name', models.CharField(max_length=55)),
                ('year_of_purchase', models.IntegerField()),
                ('brand', models.CharField(max_length=25)),
                ('vehicle_type', models.CharField(choices=[('Bike', 'Bike'), ('MiniBus', 'MiniBus')], max_length=25)),
                ('license_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_info', models.TextField()),
                ('region', models.CharField(choices=[('Lagos Only', 'Lagos Only'), ('Abuja Only', 'Abuja Only'), ('Port Harcourt Only', 'Port Harcourt Only'), ('South-South', 'South-South'), ('South-East', 'South-East'), ('South-West', 'South-West'), ('North-East', 'North-East'), ('North-Central', 'North-Central'), ('North-West', 'North-West'), ('All Regions', 'All Regions')], max_length=25)),
                ('extra_weight', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, choices=[('kilogram', 'Kilogram'), ('Gram', 'Gram')], max_length=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
