# Generated by Django 3.1.3 on 2021-06-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_distributor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_manufacturer',
        ),
    ]
