# Generated by Django 3.1.3 on 2020-11-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
