# Generated by Django 3.1.3 on 2021-06-24 16:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210617_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Must include - e.g. +234 803 123 4567', max_length=128, null=True, region=None, unique=True),
        ),
    ]
