from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('search/', views.search_view, name='search'),
    path('edit/<int:pk>/',views.edit_product, name='edit_product'),
    path('details/<int:pk>/', views.detail_view, name='detail'),
    path('search/', views.search_view , name='search'),
    path('servers/', views.servers_list , name='server'),
    path('desktop/', views.desktops_list , name='desktop'),
    path('laptops/', views.laptops_list , name='laptop'),
    path('network/', views.network_list , name='networking'),
    path('android/', views.android_list , name='android'),
    path('ios/', views.ios_list , name='ios'),
    path('my_product/', views.my_product , name='my_product'),
    path('add_product/', views.add_product , name='add_product'),
    path('delete_product/<int:pk>', views.delete_product , name='delete_product'),
    path('clothing/', views.clothing_view, name='clothing'),
    path('fabric/', views.fabrics_view, name='fabrics'),
    path('footwear/', views.footwear_view, name='footwear'),
    path('watches/', views.watch_view, name='watches'),
    path('fragrance/', views.fragrance_view, name='fragrance'),
    path('television/', views.tv_view, name='television'),
    path('ac/', views.ac_view, name='ac'),
    path('refrigerator/', views.refrigerator_view, name='refrigerator'),
    path('freezer/', views.freezer_view, name='freezer'),
    path('blender/', views.blender_view, name='blender'),
    path('dispenser/', views.dispenser_view, name='dispenser'),
    path('kettle/', views.kettle_view, name='kettle'),
    path('microwave/', views.microwave_view, name='microwave'),
    path('cooker/', views.cookers_view, name='cooker'),
    path('audio/', views.audio_view, name='audio'),
    path('furniture/', views.furniture_view, name='furniture'),
    path('bed/', views.bed_view, name='bed'),
    path('washer/', views.washers_view, name='washer'),
    path('fan/', views.fans_view, name='fan'),
    path('dashboard/', views.dashboard, name='dashboard'),
]