from django.urls import path
from . import views

urlpatterns = [
    path('clothing/<int:pk>/', views.market_clothing_view, name='market_clothing'),
    path('servers/<int:pk>/', views.market_servers_list, name='market_server'),
    path('desktop/<int:pk>/', views.market_desktops_list, name='market_desktop'),
    path('laptops/<int:pk>/', views.market_laptops_list, name='market_laptop'),
    path('network/<int:pk>/', views.market_network_list, name='market_networking'),
    path('android/<int:pk>/', views.market_android_list, name='market_android'),
    path('ios/<int:pk>/', views.market_ios_list, name='ios'),
    path('fabric/<int:pk>/', views.market_fabrics_view, name='market_fabrics'),
    path('footwear/<int:pk>/', views.market_footwear_view, name='market_footwear'),
    path('watches/<int:pk>/', views.market_watch_view, name='market_watches'),
    path('fragrance/<int:pk>/', views.market_fragrance_view, name='market_fragrance'),
    path('television/<int:pk>/', views.market_tv_view, name='market_television'),
    path('ac/<int:pk>/', views.market_ac_view, name='market_ac'),
    path('refrigerator/<int:pk>', views.market_refrigerator_view, name='market_refrigerator'),
    path('freezer/<int:pk>/', views.market_freezer_view, name='market_freezer'),
    path('blender/<int:pk>/', views.market_blender_view, name='market_blender'),
    path('dispenser/<int:pk>/', views.market_dispenser_view, name='market_dispenser'),
    path('kettle/<int:pk>/', views.market_kettle_view, name='market_kettle'),
    path('microwave/<int:pk>/', views.market_microwave_view, name='market_microwave'),
    path('cooker/<int:pk>/', views.market_cookers_view, name='market_cooker'),
    path('audio/<int:pk>/', views.market_audio_view, name='market_audio'),
    path('furniture/<int:pk>/', views.market_furniture_view, name='market_furniture'),
    path('bed/<int:pk>/', views.market_bed_view, name='market_bed'),
    path('washer/<int:pk>/', views.market_washers_view, name='market_washer'),
    path('fan/<int:pk>/', views.market_fans_view, name='fan'),
    path('category/<int:pk>/', views.market_category, name='market_category'),
]