# Generated by Django 3.1.3 on 2020-12-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201221_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='images',
            field=models.ManyToManyField(to='order.Photos'),
        ),
    ]
