# Generated by Django 3.1.3 on 2021-01-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210102_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='images',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='order.photo'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pick_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='bottom_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='photo',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='photo',
            name='rear_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='photo',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
