# Generated by Django 3.1.3 on 2021-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210102_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='pick_up',
            new_name='confirm_pickup',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='picked_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
