# Generated by Django 3.1.3 on 2021-03-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210102_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
