# Generated by Django 3.1.3 on 2021-03-04 15:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_invoices_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='bottom_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1400, 1400], upload_to='media'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='front_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1400, 1400], upload_to='media'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='main_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1400, 1400], upload_to='media'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='rear_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1400, 1400], upload_to='media'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='side_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1400, 1400], upload_to='media'),
        ),
    ]
